import Head from 'next/head'
import { useEffect } from 'react';
import CreateCiv from '../components/MainPage/createCiv';
import HomeMenu from '../components/MainPage/HomeMenu'
import Login from '../components/MainPage/Login'
import { useAuth } from '../context/authContext'
import { usePlayerDataContext } from '../context/playerDataContext';


export default function Home() {
  const { playerData } = usePlayerDataContext();
  const { user } = useAuth()

  const civList = playerData.civList

  const should = user && civList.length === 0

  useEffect(() => {
    console.log(civList)
  }, [civList])

  return (
    <>
      <Head>
        <title>CIV RPG - Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <Login />}
      {should ? <CreateCiv/> : null}
{/*       {user && civList.length > 0 && <HomeMenu/>} */}
    </>
  )
}
