import Head from 'next/head'
import CivCreator from '../components/MainPage/CivCreator';
import HomeMenu from '../components/MainPage/HomeMenu'
import Login from '../components/MainPage/Login'
import { useAuth } from '../context/authContext'
import { usePlayerDataContext } from '../context/playerDataContext';
import useFetchPlayerData from '../hooks/useFetchPlayerData';
import useFetchCivData from '../hooks/useFetchCivData';


export default function Home() {
  useFetchPlayerData()
  useFetchCivData()
  const { playerData } = usePlayerDataContext();
  const { user } = useAuth()

  const civList = playerData.civList

  return (
    <>
      <Head>
        <title>CIV RPG - Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <Login />}
      {(user && civList.length === 0 ) ? <CivCreator/> : null}
      {(user && civList.length > 0 ) ? <HomeMenu/> : null}
    </>
  )
}
