import Head from 'next/head'
import { useAuth } from '../context/authContext'
import useFetchPlayerData from '../hooks/useFetchPlayerData';
import useFetchCivData from '../hooks/useFetchCivData';
import Profile from '../components/Profile/Profile';
import { useRouter } from 'next/router';
import { useEffect } from 'react';


export default function Home() {
  const router = useRouter()
  const { user } = useAuth()

  useEffect(() => {
    if (!user) router.push('/')
  }, [user])

  useFetchPlayerData()
  useFetchCivData()

  return (
    <>
      <Head>
        <title>CIV RPG - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Profile />
    </>
  )
}