import Head from 'next/head'
import HomeMenu from '../components/HomeMenu'
import Login from '../components/Login'
import { useAuth } from '../context/AuthContext'



export default function Home() {
  const { user } = useAuth()

  return (
    <>
      <Head>
        <title>CIV RPG Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && <Login />}
      {user && <HomeMenu/>}
      
    </>
  )
}
